name: Build and publish image

on:
  push:
      branches: [master]
  workflow_dispatch:

jobs:
  build-and-publish-image:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set VERSION
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build image
        run: docker image build
          -t ghcr.io/acceptablesoftware/felix:$VERSION
          ./felix

      - name: Publish image
        run:
          # Prevent overwriting if the version already exists by
          # inspecting the manifest.
          docker manifest inspect
            ghcr.io/acceptablesoftware/felix:$VERSION
          || {
            docker push
              ghcr.io/acceptablesoftware/felix:$VERSION &&
            git config --local user.name "GitHub Action" &&
            git config --local user.email "action@github.com" &&
            git tag -a -m "version tag" "v$VERSION";
          }

      - name: Bump version and push tag
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: True
