name: build-and-publish-image

on:
  push:
    branches: [master]

jobs:
  build-and-publish-image:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    env:
      VERSION: "1.0.0"

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker image build -t felix:$VERSION ./felix

      - name: Publish image
        run: docker push ghcr.io/acceptablesoftware/felix:$VERSION
