name: Build and publish image

on:
  push:
      branches: [master]
  workflow_dispatch:

jobs:
  build-and-publish-image:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    env:
      VERSION: "1.1.1"

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker image build
          -t ghcr.io/acceptablesoftware/felix:$VERSION
          ./felix

      - name: Publish image
        run:
          # Prevent overwriting if the version already exists by
          # inspecting the manifest.
          docker manifest inspect
            ghcr.io/acceptablesoftware/felix:$VERSION
          ||
          docker push
            ghcr.io/acceptablesoftware/felix:$VERSION
